### ISSUE TITLE
Support selecting Modrinth files by version number

### ISSUE THREAD

**Issue by srnyx** [packwiz/packwiz#103]
Whenever I try, I get an error (see below for specific errors).

**Links I tried:**
- `https://modrinth.com/mod/brb/version/1.5.6`
  - `Failed installing mod: couldn't find version: 1.5.6`
- `https://cdn.modrinth.com/data/vWIaVOTE/versions/1.5.6/brb-Fabric-1.5.6.jar`
  - `Failed installing mod: Couldn't find that mod. Is it available for this version?`

**EDIT:** Just noticed the version has to be the version ID, so I'm making this into a suggestion to add support for semantic/other version support.

**Comment by comp500** [comment]
Seems like Modrinth changed the version URLs to also allow the version number in place of the version ID, whereas packwiz only checks it against the version ID as you noticed. I should be able to support that, but it would have to do a list of all the mod's files (since there isn't an endpoint for directly looking up a version from the version number).

**Comment by IntoTheVoid-900** [comment]
Is there any current workaround to use a specific version of a mod? I want to use an older Cloth Config version in my modpack because some of my mods don't work with v8.

**Comment by copygirl** [comment]
@IntoTheVoid-900 Pick the version you want, for example [this one](https://modrinth.com/mod/cloth-config/version/7.0.74%2Bforge) and replace the human-readable version in the URL with the **Version ID** found there, `c4kFw2we` in this case. Then you can run this command:

```sh
packwiz modrinth add https://modrinth.com/mod/cloth-config/version/c4kFw2we
```
