### ISSUE TITLE
URL source uses deprecated sha1 only

### ISSUE THREAD

**Issue by imsofi** [packwiz/packwiz#156]
In #137 there was introduced a new url download source for packwiz, but it seems to contain an arbitrary limitation on only using SHA1 for download hashes.

https://github.com/packwiz/packwiz/blob/c7c2ca786bd050043dc36f5a35fbe7699a29adbc/url/install.go#L60-L64

This is problematic as SHA1 has [practical methods of collision attacks](https://en.wikipedia.org/wiki/Collision_attack#Chosen-prefix_collision_attack) and have been [formally deprecated since 2011](https://en.wikipedia.org/wiki/SHA-1). Seeing how urls could link to any host, it is especially vulnerable to a malicious actor to host their own files, and abuse this weakness to drop malicious code on packwiz users without the hash changing.

While realistically this should not be a major threat for the current size of packwiz, there seems to be very little reason for forcing the use of a deprecated hashing function here.

So the solution would either be to require documentation for why sha-1 was chosen (for example if the change was API related), or changing the hashing function to act more like how modrinth has a `getBestHash` function.

**Comment by comp500** [comment]
There isn't a new URL download source as such, the packwiz format has always supported arbitrary URLs with any supported hash - the `url install` is only a convenience command for creating these. The reasoning was primarily that Modrinth required SHA1 for Modrinth modpacks, so it wouldn't need to be looked up when creating them (and is hence faster). Since then, however, the Modrinth pack format has been changed to require *both* SHA1 and SHA2-512; so this doesn't make a difference - I would happily accept a PR to change it to use a stronger hash (SHA256 would be consistent with the default index hash and cache key).

**Comment by imsofi** [comment]
> the Modrinth pack format has been changed to require both SHA1 and SHA2-512

Ahhh what a pain to require both. But the bigger question is then, does Modrinth allow pack formats with arbitrary urls? I thought they would only allow you to link to other modrinth mods.

**Comment by comp500** [comment]
The Modrinth pack format (not the same as the packwiz pack format, which shouldn't be uploaded to Modrinth) technically allows any URL, but the Modrinth website restricts the allowed URLs to Modrinth, Github and Gitlab. packwiz will download and directly include files that aren't from these sites in the Modrinth pack zip when exporting to the Modrinth pack format.
