### ISSUE TITLE
Packwiz failed identify most updated version

### ISSUE THREAD

**Issue by TheBossMagnus** [packwiz/packwiz#196]
Packwiz update --all outputs this warning 
Loading modpack...
Reading metadata files...
Checking for updates...
Warning: Modrinth versions for Fastload inconsistent between latest version number and newest release date (1.18.2.fabric.1.5.9 vs 1.5.10)

These are the incriminated releases:
![image](https://user-images.githubusercontent.com/92474350/220613014-33c3bf55-0218-4c9f-971f-5703fea86e2d.png)

**Comment by copygirl** [comment]
Author changed their release versioning from the looks of it, and Packwiz can't be sure if the new version is actually newer. I'm guessing since `1.18.2.etc` (the older release) is considered a higher version number than `1.5.10` it prints the warning and expects you to handle the ambiguity. You should be able to manually update to the specific newer release and it might be fine going forward.

**Comment by comp500** [comment]
Packwiz should still use the 1.5.10 release (it now uses release date to determine the latest version), it's just complaining since the version number `1.18.2.fabric.1.5.9` is considered higher than `1.5.10` as copygirl mentioned; so the versions *could* be out of order (it's not sure if the most recently uploaded version is actually the latest). To get rid of the warning, the author needs to fix their old version numbers to be consistent.

**Comment by TheBossMagnus** [comment]
> Packwiz should still use the 1.5.10 release (it now uses release date to determine the latest version), it's just complaining since the version number `1.18.2.fabric.1.5.9` is considered higher than `1.5.10` as copygirl mentioned; so the versions _could_ be out of order (it's not sure if the most recently uploaded version is actually the latest). To get rid of the warning, the author needs to fix their old version numbers to be consistent.

it's using the 1.5.10 (latest)
