### ISSUE TITLE
Packwiz prefers the version with wider loader support, rather than newest release

### ISSUE THREAD

**Issue by Atakku** [packwiz/packwiz#208]
When installing [spark](https://modrinth.com/mod/spark) on 1.19.2, packwiz prefers the older version 1.9.36-fabric, instead of the newer one. 
![image](https://user-images.githubusercontent.com/57140941/231117402-ce4ceb42-520e-46e2-9367-383f07d9ff4c.png)

1.9.36-fabric is different from latest 1.10.34-fabric because it has both fabric and quilt support, and for some reason packwiz prefers it to the latest (even though the modpack is using fabric)
![image](https://user-images.githubusercontent.com/57140941/231117694-fe0b9f26-856b-4524-a2cd-a6b20ff5e420.png)

**Comment by comp500** [comment]
Are you using the latest version of packwiz? This was fixed fairly recently: https://github.com/packwiz/packwiz/commit/42d8370d0cc749194922e461c145bc2cd1cc0de4

**Comment by comp500** [comment]
Hmm, the current heuristic will prefer versions supporting Quilt over Fabric regardless of which loader is currently being used. Making it prefer Fabric if Fabric is being used would work for your usage, but it is still not the correct behaviour for those using Quilt.

I think I might be able to resolve this by considering two versions as equal wrt loader when the loader lists both have a loader in common that is also supported by the pack. This does make the version ordering code even more complicated and has some edge cases, so I'm not entirely sure this is a good idea.

**Comment by unilock** [comment]
This appears to still be an issue with mods from CurseForge.

For example, with a 1.19.2 Quilt modpack with [spark](https://www.curseforge.com/minecraft/mc-mods/spark) added (with the latest version manually specified on addition):

```
Checking for updates...
Updates found:
spark: spark-1.10.37-fabric.jar -> spark-1.9.36-fabric.jar
Do you want to update? [Y/n]:
```

spark version [1.9.36](https://www.curseforge.com/minecraft/mc-mods/spark/files/3984406) was the last version to explicitly state Quilt support, but the latest version for *Fabric* (which also works on Quilt) is [1.10.37](https://www.curseforge.com/minecraft/mc-mods/spark/files/4505310).

This also occurs with many other mods - [Adaptive Tooltips](https://www.curseforge.com/minecraft/mc-mods/adaptive-tooltips/files?gameVersionTypeId=4&version=1.19.2), [More Totems of Undying](https://www.curseforge.com/minecraft/mc-mods/more-totems-of-undying/files?version=1.19.2&gameVersionTypeId=4), [Survival Island](https://www.curseforge.com/minecraft/mc-mods/survival-island/files?version=1.19.2&gameVersionTypeId=4), etc. (Note the "Fabric" vs. "Fabric + 1" under the "Mod Loaders" column.)

**Comment by comp500** [comment]
Unfortunately with CurseForge it's somewhat more complicated to implement. The "latest files" list only specifies 1 loader, so packwiz can't distinguish between [Quilt, Fabric] and [Quilt] (as the former should be considered equal to [Fabric] whereas the latter should not). So... I guess it would have to download the metadata for all of the Fabric/Quilt files (for the supported game versions) to determine the right ordering?

**Comment by unilock** [comment]
Does the API allow specifying the modloader to get the latest version of a mod for? If so, would it be possible to get both the latest Fabric version *and* the latest Quilt version, then compare to see which has a newer release date?

Although, a new problem would arise when a mod provides *separate* Fabric and Quilt versions, and the Fabric version just so happens to be published sooner than the Quilt one...

One workaround I could think of would be to specify the modloader *per mod* (in its metadata), but the user would then have to know in advance whether a given mod has a newer version for Fabric than for Quilt, especially if they're just adding it to packwiz for the first time (since packwiz wouldn't inherently know that there's a newer *Fabric-like* version available).

Alternatively, to add on to your idea, packwiz could get the full metadata for *only the latest* Fabric version and the latest Quilt version of a mod, then only choose the Fabric version if it's newer (i.e. more recently published) than the Quilt version *and* if the Quilt version is marked as supporting both Fabric *and* Quilt, since we can then assume that there *aren't* separate Fabric and Quilt releases of the mod.

**Comment by unilock** [comment]
Re: last point: something like this:

![Untitled Diagram drawio](https://github.com/packwiz/packwiz/assets/11802133/2975185e-f0ee-4f49-9a3d-5878592edea7)

**Comment by unilock** [comment]
This is now also an issue with Forge / NeoForge (for 1.20.1) :(
