### ISSUE TITLE
Exported Curseforge packs are not compatible with ATLauncher

### ISSUE THREAD

**Issue by xieve** [packwiz/packwiz#263]
When trying to import a zip file generated by `packwiz curseforge export`, it fails with the error:
```
com.atlauncher.network.DownloadException: https://api.curseforge.com/v1/mods/0 request wasn't successful: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.curseforge.com/v1/mods/0}
```
This is due to this line in the manifest.json, directly below `"author"`, above `"files"`:
```
  "projectID": 0,
```
Deleting that line makes it work. I have not tested other launchers.

**Comment by comp500** [comment]
You can specify which project ID your curseforge pack has in `pack.toml`, with the following format:

```
[export.curseforge]
project-id = 1234
```

I believe packs without a project ID (or with a project ID of 0) do still work in the CurseForge launcher though - this could still be fixed in ATLauncher, you shouldn't need to upload a pack to CurseForge to import it.
